export const data = [
  {
    id: 1,
    name: "Бесплатный кейс 24 часа",
    item_name: "кадзуха",
    real_price: 232,
    discount_price: 678,
    image: "/custom-data/card-1.png",
  },
  {
    id: 2,
    name: "Бесплатный кейс 24 часа",
    item_name: "кли",
    real_price: 232,
    discount_price: 678,
    image: "/custom-data/card-2.png",
  },
  {
    id: 3,
    name: "Бесплатный кейс 24 часа",
    item_name: "ху-тао",
    real_price: 232,
    discount_price: 678,
    image: "/custom-data/card-3.png",
  },
  {
    id: 4,
    name: "Бесплатный кейс 24 часа",
    item_name: "сяо",
    real_price: 232,
    discount_price: 678,
    image: "/custom-data/card-4.png",
  },
  {
    id: 5,
    name: "Бесплатный кейс 24 часа",
    item_name: "итто",
    real_price: 232,
    discount_price: 678,
    image: "/custom-data/card-5.png",
  },
  {
    id: 6,
    name: "Бесплатный кейс 24 часа",
    item_name: "тигнари",
    real_price: 122,

    image: "/custom-data/card-6.png",
  },
  {
    id: 7,
    name: "Бесплатный кейс 24 часа",
    item_name: "аяка",
    real_price: 1233,
    image: "/custom-data/card-7.png",
  },
  {
    id: 8,
    name: "Бесплатный кейс 24 часа",
    item_name: "дэхья",
    real_price: 445,
    image: "/custom-data/card-8.png",
  },
  {
    id: 9,
    name: "Бесплатный кейс 24 часа",
    item_name: "нилу",
    real_price: 556,
    image: "/custom-data/card-9.png",
  },
  {
    id: 10,
    name: "Бесплатный кейс 24 часа",
    item_name: "ёимия",
    real_price: 344,

    image: "/custom-data/card-10.png",
  },
];
